export const defaultNutrients: { id: number, name: string, displayName: string, displayNameRu: string, unit: string }[] = [
    { id: 1, name: 'protein', displayName: 'Protein', displayNameRu: 'Белки', unit: 'g' },
    { id: 2, name: 'fats', displayName: 'Fats', displayNameRu: 'Жиры', unit: 'g' },
    { id: 3, name: 'carbohydrates', displayName: 'Carbohydrates', displayNameRu: 'Углеводы', unit: 'g' },
    { id: 4, name: 'sugar', displayName: 'Sugar', displayNameRu: 'Сахар', unit: 'g' },
    { id: 5, name: 'starch', displayName: 'Starch', displayNameRu: 'Крахмал', unit: 'g' },
    { id: 6, name: 'fiber', displayName: 'Fiber', displayNameRu: 'Клетчатка', unit: 'g' },
    { id: 7, name: 'energy', displayName: 'kcal', displayNameRu: 'Энергия', unit: 'kcal' },
    { id: 8, name: 'water', displayName: 'Water', displayNameRu: 'Вода', unit: 'g' },

    { id: 9, name: 'iron', displayName: 'Iron', displayNameRu: 'Железо', unit: 'mg' },
    { id: 10, name: 'magnesium', displayName: 'Magnesium', displayNameRu: 'Магний', unit: 'mg' },
    { id: 11, name: 'phosphorus', displayName: 'Phosphorus', displayNameRu: 'Фосфор', unit: 'mg' },
    { id: 12, name: 'potassium', displayName: 'Potassium', displayNameRu: 'Калий', unit: 'mg' },
    { id: 13, name: 'sodium', displayName: 'Sodium', displayNameRu: 'Натрий', unit: 'mg' },
    { id: 14, name: 'zinc', displayName: 'Zinc', displayNameRu: 'Цинк', unit: 'mg' },
    { id: 15, name: 'copper', displayName: 'Copper', displayNameRu: 'Медь', unit: 'μg' },
    { id: 16, name: 'manganese', displayName: 'Manganese', displayNameRu: 'Марганец', unit: 'μg' },
    { id: 17, name: 'selenium', displayName: 'Selenium', displayNameRu: 'Селен', unit: 'μg' },
    { id: 18, name: 'iodine', displayName: 'Iodine', displayNameRu: 'Йод', unit: 'μg' },

    { id: 19, name: 'vitaminA', displayName: 'Vitamin A', displayNameRu: 'Витамин A', unit: 'μg' },
    { id: 20, name: 'vitaminB1', displayName: 'Vitamin B1', displayNameRu: 'Витамин B1', unit: 'mg' },
    { id: 21, name: 'vitaminB2', displayName: 'Vitamin B2', displayNameRu: 'Витамин B2', unit: 'mg' },
    { id: 22, name: 'vitaminB3', displayName: 'Vitamin B3', displayNameRu: 'Витамин B3', unit: 'mg' },
    { id: 22, name: 'vitaminB4', displayName: 'Vitamin B4 (Choline)', displayNameRu: 'Витамин B4 (Холин)', unit: 'mg' },
    { id: 23, name: 'vitaminB5', displayName: 'Vitamin B5', displayNameRu: 'Витамин B5', unit: 'mg' },
    { id: 24, name: 'vitaminB6', displayName: 'Vitamin B6', displayNameRu: 'Витамин B6', unit: 'mg' },
    { id: 26, name: 'vitaminB9', displayName: 'Vitamin B9', displayNameRu: 'Витамин B9', unit: 'μg' },
    { id: 27, name: 'vitaminB12', displayName: 'Vitamin B12', displayNameRu: 'Витамин B12', unit: 'μg' },
    { id: 28, name: 'vitaminC', displayName: 'Vitamin C', displayNameRu: 'Витамин C', unit: 'mg' },
    { id: 29, name: 'vitaminD', displayName: 'Vitamin D', displayNameRu: 'Витамин D', unit: 'μg' },
    { id: 30, name: 'vitaminE', displayName: 'Vitamin E', displayNameRu: 'Витамин E', unit: 'mg' },
    { id: 31, name: 'vitaminK', displayName: 'Vitamin K', displayNameRu: 'Витамин K', unit: 'μg' },
    { id: 32, name: 'betaCarotene', displayName: 'Beta-carotene', displayNameRu: 'Бета-каротин', unit: 'μg' },
    { id: 33, name: 'alphaCarotene', displayName: 'Alpha-carotene', displayNameRu: 'Альфа-каротин', unit: 'μg' }
];
