import raw from './catalog.json';
import type { ProductRow } from '@/shared/lib/dexie/schema';

// System catalog. Read-only, ships with the JS bundle, regenerated by
// `apps/disher-backend-3.0/scripts/build-catalog.ts` from the seed
// source-of-truth (combined-foods.json) and committed.
//
// Catalog rows share `ProductRow` shape with user products so a single mapper
// works on both. There is no `/api/catalog` endpoint and no Dexie catalog
// table — see apps/food-calc/tds/ANALYSIS/zero-base-rewrite-2026-05-09.md.

// Catalog rows are build-route data: read-only, never written or merged, so
// they carry no `updated_at` (a user-route/LWW field). Cast through `unknown`
// since the JSON is structurally ProductRow minus that one sync column.
export const catalog: ReadonlyArray<ProductRow> = raw as unknown as ProductRow[];

const byId = new Map<string, ProductRow>(catalog.map((r) => [r.id, r]));

export function findCatalogProduct(id: string): ProductRow | undefined {
  return byId.get(id);
}

export function isCatalogId(id: string): boolean {
  return byId.has(id);
}
