export enum ModalType {

    COPY_SCHEDULE_ITEMS_TO_ANOTHER_DAY = 'COPY_SCHEDULE_ITEMS_TO_ANOTHER_DAY',
    COPY_SCHEDULE_ITEMS_TO_DISH = 'COPY_SCHEDULE_ITEMS_TO_DISH',
    COPY_DISH_ITEMS_TO_ANOTHER_DISH = 'COPY_DISH_ITEMS_TO_ANOTHER_DISH',
    COPY_DISH_ITEMS_TO_SCHEDULE = 'COPY_DISH_ITEMS_TO_SCHEDULE',

    SELECT = 'select',

    CREATE_DISH_FROM_SCHEDULE = 'CREATE_DISH_FROM_SCHEDULE',

    DISH_CREATE = 'DISH_CREATE',
    DISH_EDIT = 'DISH_EDIT',

    PULSE_PHYSICAL_ACTIVITY = 'PULSE_PHYSICAL_ACTIVITY',

    SCHEDULE_FOOD_ADD = 'SCHEDULE_FOOD_ADD',
    SCHEDULE_FOOD_EDIT = 'SCHEDULE_FOOD_EDIT',
    SCHEDULE_EVENT_ADD = 'SCHEDULE_EVENT_ADD',
    SCHEDULE_EVENT_EDIT = 'SCHEDULE_EVENT_EDIT',

    SEARCH_FOOD = 'SEARCH_FOOD'
}
