export enum ModalType {
    CONFIRMATION_REMOVE_DISHES = 'CONFIRMATION_REMOVE_DISHES',
    CONFIRMATION_REMOVE_DISH_ITEMS = 'CONFIRMATION_REMOVE_DISH_ITEMS',
    CONFIRMATION_REMOVE_SCHEDULE_FOOD = 'CONFIRMATION_REMOVE_SCHEDULE_FOOD',
    CONFIRMATION_REMOVE_SCHEDULE_EVENTS = 'CONFIRMATION_REMOVE_SCHEDULE_EVENTS',
    CONFIRMATION_REMOVE_DAILY_NORM = 'CONFIRMATION_REMOVE_DAILY_NORM',
    CONFIRMATION_REMOVE_USER_FOOD = 'CONFIRMATION_REMOVE_USER_FOOD',

    COPY_SCHEDULE_ITEMS_TO_ANOTHER_DAY = 'COPY_SCHEDULE_ITEMS_TO_ANOTHER_DAY',
    COPY_SCHEDULE_ITEMS_TO_DISH = 'COPY_SCHEDULE_ITEMS_TO_DISH',
    COPY_DISH_ITEMS_TO_ANOTHER_DISH = 'COPY_DISH_ITEMS_TO_ANOTHER_DISH',
    COPY_DISH_ITEMS_TO_SCHEDULE = 'COPY_DISH_ITEMS_TO_SCHEDULE',

    SELECT = 'select',

    CREATE_DISH_FROM_SCHEDULE = 'CREATE_DISH_FROM_SCHEDULE',
    CREATE_FOOD = 'CREATE_FOOD',
    CREATE_DISH = 'CREATE_DISH',

    DISH_CREATE = 'DISH_CREATE',
    DISH_EDIT = 'DISH_EDIT',

    PULSE_PHYSICAL_ACTIVITY = 'PULSE_PHYSICAL_ACTIVITY',

    SCHEDULE_FOOD_ADD = 'SCHEDULE_FOOD_ADD',
    SCHEDULE_FOOD_EDIT = 'SCHEDULE_FOOD_EDIT',
    SCHEDULE_EVENT_ADD = 'SCHEDULE_EVENT_ADD',
    SCHEDULE_EVENT_EDIT = 'SCHEDULE_EVENT_EDIT'
}

export type ConfirmationModals = ModalType.CONFIRMATION_REMOVE_DISHES
    | ModalType.CONFIRMATION_REMOVE_SCHEDULE_FOOD
    | ModalType.CONFIRMATION_REMOVE_SCHEDULE_EVENTS
    | ModalType.CONFIRMATION_REMOVE_DISH_ITEMS
    | ModalType.CONFIRMATION_REMOVE_DAILY_NORM
    | ModalType.CONFIRMATION_REMOVE_USER_FOOD