export enum ModalType {
    CONFIRMATION_REMOVE_DISHES = 'CONFIRMATION_REMOVE_DISHES',
    CONFIRMATION_REMOVE_DISH_ITEMS = 'CONFIRMATION_REMOVE_DISH_ITEMS',
    CONFIRMATION_REMOVE_SCHEDULE_FOOD = 'CONFIRMATION_REMOVE_SCHEDULE_FOOD',
    CONFIRMATION_REMOVE_SCHEDULE_EVENTS = 'CONFIRMATION_REMOVE_SCHEDULE_EVENTS',

    COPY_SCHEDULE_ITEMS_TO_ANOTHER_DAY = 'COPY_SCHEDULE_ITEMS_TO_ANOTHER_DAY',
    COPY_SCHEDULE_ITEMS_TO_DISH = 'COPY_SCHEDULE_ITEMS_TO_DISH',
    COPY_DISH_ITEMS_TO_ANOTHER_DISH = 'COPY_DISH_ITEMS_TO_ANOTHER_DISH',
    COPY_DISH_ITEMS_TO_SCHEDULE = 'COPY_DISH_ITEMS_TO_SCHEDULE',

    SELECT = 'select',

    CREATE_DISH_FROM_SCHEDULE = 'CREATE_DISH_FROM_SCHEDULE',
    CREATE_FOOD = 'CREATE_FOOD',
    CREATE_DISH = 'CREATE_DISH',
}

export type ConfirmationModals = ModalType.CONFIRMATION_REMOVE_DISHES
    | ModalType.CONFIRMATION_REMOVE_SCHEDULE_FOOD
    | ModalType.CONFIRMATION_REMOVE_SCHEDULE_EVENTS
    | ModalType.CONFIRMATION_REMOVE_DISH_ITEMS