export const defaultNutrients: { id: number, name: string, displayName: string, nameRu: string, unit: string }[] = [
    { id: 1, name: 'protein', displayName: 'Protein', nameRu: 'Белки', unit: 'g' },
    { id: 2, name: 'fats', displayName: 'Fats', nameRu: 'Жиры', unit: 'g' },
    { id: 3, name: 'carbohydrates', displayName: 'Carbohydrates', nameRu: 'Углеводы', unit: 'g' },
    { id: 4, name: 'sugar', displayName: 'Sugar', nameRu: 'Сахар', unit: 'g' },
    { id: 5, name: 'starch', displayName: 'Starch', nameRu: 'Крахмал', unit: 'g' },
    { id: 6, name: 'fiber', displayName: 'Fiber', nameRu: 'Клетчатка', unit: 'g' },
    { id: 7, name: 'energy', displayName: 'kcal', nameRu: 'Энергия', unit: 'kcal' },
    { id: 8, name: 'water', displayName: 'Water', nameRu: 'Вода', unit: 'g' },

    { id: 9, name: 'iron', displayName: 'Iron', nameRu: 'Железо', unit: 'mg' },
    { id: 10, name: 'magnesium', displayName: 'Magnesium', nameRu: 'Магний', unit: 'mg' },
    { id: 11, name: 'phosphorus', displayName: 'Phosphorus', nameRu: 'Фосфор', unit: 'mg' },
    { id: 12, name: 'potassium', displayName: 'Potassium', nameRu: 'Калий', unit: 'mg' },
    { id: 13, name: 'sodium', displayName: 'Sodium', nameRu: 'Натрий', unit: 'mg' },
    { id: 14, name: 'zinc', displayName: 'Zinc', nameRu: 'Цинк', unit: 'mg' },
    { id: 15, name: 'copper', displayName: 'Copper', nameRu: 'Медь', unit: 'μg' },
    { id: 16, name: 'manganese', displayName: 'Manganese', nameRu: 'Марганец', unit: 'μg' },
    { id: 17, name: 'selenium', displayName: 'Selenium', nameRu: 'Селен', unit: 'μg' },
    { id: 18, name: 'iodine', displayName: 'Iodine', nameRu: 'Йод', unit: 'μg' },

    { id: 19, name: 'vitaminA', displayName: 'Vitamin A', nameRu: 'Витамин A', unit: 'μg' },
    { id: 20, name: 'vitaminB1', displayName: 'Vitamin B1', nameRu: 'Витамин B1', unit: 'mg' },
    { id: 21, name: 'vitaminB2', displayName: 'Vitamin B2', nameRu: 'Витамин B2', unit: 'mg' },
    { id: 22, name: 'vitaminB3', displayName: 'Vitamin B3', nameRu: 'Витамин B3', unit: 'mg' },
    { id: 23, name: 'vitaminB4', displayName: 'Vitamin B4 (Choline)', nameRu: 'Витамин B4 (Холин)', unit: 'mg' },
    { id: 24, name: 'vitaminB5', displayName: 'Vitamin B5', nameRu: 'Витамин B5', unit: 'mg' },
    { id: 25, name: 'vitaminB6', displayName: 'Vitamin B6', nameRu: 'Витамин B6', unit: 'mg' },
    { id: 26, name: 'vitaminB9', displayName: 'Vitamin B9', nameRu: 'Витамин B9', unit: 'μg' },
    { id: 27, name: 'vitaminB12', displayName: 'Vitamin B12', nameRu: 'Витамин B12', unit: 'μg' },
    { id: 28, name: 'vitaminC', displayName: 'Vitamin C', nameRu: 'Витамин C', unit: 'mg' },
    { id: 29, name: 'vitaminD', displayName: 'Vitamin D', nameRu: 'Витамин D', unit: 'μg' },
    { id: 30, name: 'vitaminE', displayName: 'Vitamin E', nameRu: 'Витамин E', unit: 'mg' },
    { id: 31, name: 'vitaminK', displayName: 'Vitamin K', nameRu: 'Витамин K', unit: 'μg' },
    { id: 32, name: 'betaCarotene', displayName: 'Beta-carotene', nameRu: 'Бета-каротин', unit: 'μg' },
    { id: 33, name: 'alphaCarotene', displayName: 'Alpha-carotene', nameRu: 'Альфа-каротин', unit: 'μg' }
];
