import { DISH_PRODUCT_INPUT_IDS } from '../useDishProductFlow';

export const DISH_MODAL_INPUT_IDS = {
  SEARCH_INPUT: DISH_PRODUCT_INPUT_IDS.SEARCH_CREATE_INPUT,
  QUANTITY_INPUT: DISH_PRODUCT_INPUT_IDS.QUANTITY_CREATE_INPUT,
  DETAILS_INPUT: DISH_PRODUCT_INPUT_IDS.DETAILS_CREATE_INPUT,
} as const;
